BEGIN TRANSACTION;

ALTER TABLE categories ADD COLUMN goal_amount INTEGER DEFAULT NULL;
ALTER TABLE categories ADD COLUMN goal_type TEXT DEFAULT NULL;
ALTER TABLE categories ADD COLUMN goal_target_month TEXT DEFAULT NULL;

COMMIT;
